# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all availableplugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run all unit tests"
  lane :test do
    scan(
      scheme: "PunchPad",
      clean: true,
      device: "iPhone 15"
    )
  end

  desc "Increment build"
  lane:increment_build do 
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    commit_version_bump(
      message: "Build number bump [ci skip]",
      xcodeproj: "PunchPad.xcodeproj"
    )
  end
end
